---
title: "Reflection on the use of GenAI"
---

# 🤖 GenAI tool that I have used:
I have used **ChatGPT** as my GenAI tool. **ChatGPT** assisted me by providing simpler explanations and examples on technical concept related to programming, web development and mathematics. It was particularly useful especially when **ChatGPT** is able to adjust to my ability to absorb knowledge and provide explanations that are easier to understand. It also helped me debug errors, and improve the clarity of my codes.

# ⚙️ How GenAI tools can assist me for my future study/work
GenAI tools such as ChatGPT can be valuable in supporting my current studies:
- Clarify complex technical concepts related to programming, blockchain and mathematics
- Assist in problem-solving by suggesting possible approaches or debugging steps
- - Allow customised instructions so that the GenAI tool is not a “yes-only” system, but can actively challenge assumptions, point out mistakes, and provide corrective feedback when needed. This encourages critical thinking rather than passive acceptance of generated responses.
